blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/your-username/simple-websocket-proxy/discussions
    about: Ask questions, share ideas, and connect with the community
  - name: 📚 Documentation
    url: https://github.com/your-username/simple-websocket-proxy#readme
    about: Read the project documentation and setup guides
  - name: 🔒 Security Issues
    url: https://github.com/your-username/simple-websocket-proxy/security/policy
    about: Report security vulnerabilities privately