name: ✨ Feature Request
description: Suggest a new feature for the WebSocket Proxy
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for suggesting a feature! ✨
        
        Please fill out this form to help us understand your feature request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm before submitting
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have read the documentation to ensure this feature doesn't already exist
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - ws-proxy (WebSocket proxy server)
        - ops-ui (Operations dashboard)
        - docker (containerization)
        - ci-cd (GitHub Actions workflows)
        - documentation
        - architecture
        - other
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New functionality
        - Performance improvement
        - Developer experience
        - Security enhancement
        - Configuration option
        - API enhancement
        - UI/UX improvement
        - Monitoring/observability
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to happen?
      placeholder: |
        A clear and concise description of what you want to happen.
        Include specific details about the implementation if you have ideas.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: |
        A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. As a [user type], I want [goal] so that [benefit]
        2. When [scenario], this feature would [outcome]
        3. This would help with [specific problem]
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Important for project success
        - Critical - Blocking project progress
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Small changes or additions
        - Medium - Moderate changes across multiple files
        - Complex - Significant changes or new architecture
        - Unknown - Need technical assessment

  - type: checkboxes
    id: scope
    attributes:
      label: Scope
      description: What areas would this feature impact?
      options:
        - label: Breaking changes to existing API
        - label: New configuration options
        - label: Database schema changes
        - label: New dependencies
        - label: Documentation updates
        - label: Security implications
        - label: Performance considerations

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: Any technical implementation details or constraints
      placeholder: |
        - API design considerations
        - Database changes needed
        - Third-party integrations
        - Performance requirements
        - Security considerations

  - type: textarea
    id: examples
    attributes:
      label: Examples and Mockups
      description: Code examples, API designs, or UI mockups
      render: markdown
      placeholder: |
        ```javascript
        // Example API usage
        const proxy = new WebSocketProxy({
          newFeature: true
        });
        ```

  - type: textarea
    id: testing
    attributes:
      label: Testing Considerations
      description: How should this feature be tested?
      placeholder: |
        - Unit tests needed
        - Integration tests needed
        - E2E tests needed
        - Manual testing scenarios
        - Performance testing requirements

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature introduce breaking changes?
      options:
        - label: No breaking changes
        - label: Minor breaking changes (can be mitigated)
        - label: Major breaking changes (requires new major version)
        - label: Unsure about breaking changes

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or links about the feature request
      placeholder: |
        - Links to relevant discussions
        - Screenshots or mockups
        - Related issues or PRs
        - External resources or documentation

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to submit a pull request for this feature
        - label: I can help with design and planning
        - label: I can provide testing and feedback
        - label: I can help with documentation
        - label: I need help implementing this but can provide guidance